owner: MigraineKR
repo: upptime

sites:
  - name: ihs-headache.org
    url: https://ihs-headache.org/
  - name: headache.or.kr
    url: https://www.headache.or.kr/index.php
  - name: migrainecluster.com
    url: http://www.migrainecluster.com/
  - name: americanheadachesociety.org
    url: https://americanheadachesociety.org/
  - name: americanmigrainefoundation.org
    url: https://americanmigrainefoundation.org/
  - name: headaches.org
    url: https://headaches.org/
  - name: clusterbusters.org
    url: https://clusterbusters.org/
  - name: daniellefoundation.org
    url: https://daniellefoundation.org/
  - name: headachemigraine.org
    url: https://headachemigraine.org/
  - name: jhsnet.net
    url: https://www.jhsnet.net/
  - name: jhsnet.net/english
    url: https://www.jhsnet.net/english.html
  - name: migraine.org.au
    url: https://www.migraine.org.au/
  - name: headacheaustralia.org.au
    url: https://headacheaustralia.org.au/
  - name: migrainecanada.org
    url: https://migrainecanada.org/
  - name: migrainequebec.org
    url: https://migrainequebec.org/
  - name: migreeni.org
    url: https://migreeni.org/
  - name: migraine.ie
    url: http://migraine.ie/
  - name: bezzymigraine.com
    url: https://www.bezzymigraine.com/
  - name: hodepinenorge.no
    url: https://hodepinenorge.no/
  - name: emhalliance.org
    url: https://www.emhalliance.org/
  - name: efna.net
    url: https://www.efna.net/
  - name: chronicmigraineawareness.org
    url: https://chronicmigraineawareness.org/
  - name: migraineworldsummit.com
    url: https://migraineworldsummit.com/
  - name: migraineagain.com
    url: https://www.migraineagain.com/
  - name: migrainetrust.org
    url: https://migrainetrust.org/
  - name: migrainedisorders.org
    url: https://www.migrainedisorders.org/
  - name: migrainecollaborative.org
    url: https://migrainecollaborative.org/
  - name: parentingwithmigraine.com
    url: https://parentingwithmigraine.com/
  - name: milesformigraine.org
    url: https://www.milesformigraine.org/
  - name: shadesformigraine.org
    url: https://shadesformigraine.org/
  - name: mymigrainelife.net
    url: https://www.mymigrainelife.net/
  - name: headachemigraineforum.org
    url: https://www.headachemigraineforum.org/
  - name: migraine.com
    url: https://migraine.com/
  - name: worldheadachesociety.org
    url: https://worldheadachesociety.org/
  - name: patientadvocate.org
    url: https://www.patientadvocate.org/

status-website:
  cname: upptime.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime | Migraine
  introTitle: "**Upptime** for Migraine"
  introMessage: 두통 관련 사이트 웹모니터
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: News
      href: https://go.migraine.kr/update
    - title: Community
      href: https://go.migraine.kr/community
