owner: MigraineKR
repo: upptime

sites:
  - name: headache.or.kr
    url: https://www.headache.or.kr/index.php
  - name: migrainecluster.com
    url: http://www.migrainecluster.com/
  - name: americanheadachesociety.org
    url: https://americanheadachesociety.org/
    
status-website:
  cname: upptime.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime | Migraine
  introTitle: "**Upptime** for Migraine"
  introMessage: 두통 관련 사이트 웹모니터
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: News
      href: https://go.migraine.kr/update
    - title: Discord
      href: https://go.migraine.kr/community
